# Project
version=8.38
group=com.natamus

# Common
minecraft_version=26.2
minecraft_display_version=26.2.0

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric
#  https://fabricmc.net/develop/
fabric_api_version=0.152.1+26.2
fabric_loader_version=0.19.3

# Forge
#  https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=65.0.0

# NeoForge
#  https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.1-beta

# Mod Options
mod_name=collective
mod_author=Serilum
mod_id=collective

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Java
java_version=25